### ISSUE TITLE
Using the enter key in the user-list breaks greeter

### ISSUE THREAD

**Issue by Ryex** [Antergos/lightdm-webkit-theme-antergos#14]
exactly what it says on the tin.

if you've clicked on the time to bring up the user list (only one user in my setup) and then hit enter to select the highlighted user. the user-list hides the users' box you selected hides, and the password box does not appear. This leave a white box with the welcome bar on top and the power options below but nothing else. lightdm has to be restated for login to continue.

**Comment by lots0logs** [comment]
Hi, What about when you don't click the clock first and just press enter or space bar instead. Does it go straight to the password prompt? (It should, but their may be a regression)

**Comment by jzbl** [comment]
I'm getting the exact same issue on:

antergos/lightdm-webkit-theme-antergos 2.0.7-2 [installed]
    The official greeter theme of Antergos Linux
antergos/lightdm-webkit2-greeter 0.1.2-8 [installed]
    A webkit2 greeter for LightDM

**Comment by jzbl** [comment]
@lots0logs - the issue only reoccurs when you mouseclick on the clock, then press enter. The user choice box and the password prompt hides and you cannot do anything...
Using enter key twice to get to password prompt works normally - it is just a *very* annoying bug.

**Comment by Ryex** [comment]
Confirmed.
Using enter or space takes you to the password box. clicking on the clock
renders the greeter unusable and a lightdm restart is required.

**Comment by axaxs** [comment]
I notice this also.  As a workaround, at least from the lock screen, right clicking and choosing Reload should bring it back.

**Comment by Ryex** [comment]
This behavior seems to be absent in recent versions

**Comment by lots0logs** [comment]
@Ryex thanks for confirming!
