### ISSUE TITLE
Aesthetic Bug - White box draws under login manager when password is incorrect

### ISSUE THREAD

**Issue by raidermax** [Antergos/lightdm-webkit-theme-antergos#17]
A while box will draw under the login manager if you enter in your password incorrectly, wait for the red prompt to appear and click on the password box field and begin typing again. Everything is still functional, hence why its just an appearance bug. 

I guess the simplest fix would be to make the red prompt go away once typing starts in the field again, Idk though I am no coder, just giving ideas.

I love this theme a lot, thanks!

**Comment by lots0logs** [comment]
I think this has been fixed in the latest version. If it still occurs please let me know so I can reopen the issue. Thanks.

**Comment by raidermax** [comment]
Hi lotsologs, happy new year!

Sadly to say this "problem" still persists in the latest version. I am on version 2.0.0.1 according to pamac on Arch Linux.

**Comment by lots0logs** [comment]
Fyi, this is now being tracked on #30

**Comment by raidermax** [comment]
@lots0logs I may be due for an apology. I was still using an old version of this theme somehow. I removed what I had and installed the new lightdm-webkit-archlinux package available on the AUR and it is fabulous and works wonderfully. So I think maybe this is indeed fixed?

Thanks again sooo much for your work, this is really a beautiful theme and you have an eye for design no other Linux dev can match (really there is not a better one than this which is kind of sucks for desktop Linux, wish there were more like yours). Thanks again and I hope you enjoy your day!

**Comment by lots0logs** [comment]
Thanks for the status update :+1:

**Comment by raidermax** [comment]
@lots0logs Okay I think you're going to hate me again but I am experiencing that same exact bug as I did in OP...honestly I feel like just forget about it because you've tried fixing it and it just keeps coming back so its probably something with lightdm updates or something weird/changing as I am on Arch Linux. Just wanted to notify you though.
