### ISSUE TITLE
HIDPI

### ISSUE THREAD

**Issue by sils1297** [Antergos/lightdm-webkit-theme-antergos#18]
Hey, GNOME is handling HIDPI nicely, however lightdm isn't.  You should do something about that IMO, makes logging in hard as everything's really small.

**Comment by lots0logs** [comment]
Your gnome display configuration should not be applied until after logging in. I don't have a HIDPI display so I'm afraid I cannot test this. You can add a call to xrandr to lightdm.conf to be ran before the greeter is launched to correct the issue.

**Comment by sils1297** [comment]
Thanks. FYI I don't need a workaround, I simply replaced it with GDM. This bug is so you are aware of this issue for other users without the technical knowledge to correct this by themselves.

**Comment by lots0logs** [comment]
I see, well I dont think its anything we can control from the lightdm theme so it would need to be reported upstream to lightdm devs. If I have time I'll try to look into it though. Thanks!
