### ISSUE TITLE
Very Slow behavior

### ISSUE THREAD

**Issue by niccolatorres** [Antergos/lightdm-webkit-theme-antergos#21]
I have this strange behavior using this theme. I am using antergos os and this greeter is very slow at startup.
Background Image loads in 1/5 steps by 1 second each step
every action takes some time and appears laggy (select background image, click on clock to login)
The only thing that is normal and is not laggy is password input and login button.

**Comment by lots0logs** [comment]
@niccolatorres Could you confirm whether this is still an issue with the latest versions of webkit2greeter and the theme?

**Comment by niccolatorres** [comment]
@lots0logs 
The issue no longer exists. I am almost totally sure that it was been solved with webkit2 fixes

**Comment by lots0logs** [comment]
Okay great. Thanks for following up :smile:
