### ISSUE TITLE
Upon updating no longer able to log in using lightdm

### ISSUE THREAD

**Issue by djringjr** [Antergos/lightdm-webkit-theme-antergos#22]
Can no longer get to click on USER and then enter password.  If I click on around the clock, I get just a developed white screen that just stays that way until I press Ctrl+Alt+Backspace to kill Xorg server.

If I disable lightdm.service and install, enable, and start gdm.service, I can log in fine.

But lightdm with Antergos lightdm-webkit-theme-antergos no longer works.

I have just seen the instructions:

Remove the folder antergos created in /usr/share/lightdm-webkit/themes/
Restore the webkit-theme property of the /etc/lightdm/lightdm-webkit-greeter.conf file

I will try this, I have tried all other work arounds and I cannot proceed beyond the pictures with the clock, I cannot see USERNAME and I cannot log in or select which DE I want to use.

**Comment by karasu** [comment]
https://forum.antergos.com/topic/3015/attn-antergos-lightdm-theme-users/2

**Comment by BuZZ-dEE** [comment]
I bot an update for lightdm today. Now I don't get the white screen, but now it I really can not login anymore. I enter my password and nothing happens. I also can not switch to tty, so what can I do now to login and switch to gdm?
