### ISSUE TITLE
Blank white screen after clicking clock

### ISSUE THREAD

**Issue by YottaSecond** [Antergos/lightdm-webkit-theme-antergos#25]
I'm experiencing an issue where the initial screen with the clock loads fine, but once I click on it the whole screen goes white.

I can still see a cursor, and it switches to a hand when it highlights over the name section, so I can technically still log in.

I'm on Arch Linux and installed the "lightdm-webkit-theme-antergos 2.2.3-1" package from the AUR. I have kernel 4.2.5-1 and I'm using my laptop's onboard intel card (I have the "mesa" and "xf86-video-intel") packages installed.

I'd be happy to help debug if there are any logs I can look into, but I'm not sure what's available. Has anybody else run into this issue?

**Comment by lots0logs** [comment]
Hi, do you have the latest version of our webkit2 greeter installed?

**Comment by YottaSecond** [comment]
I thought I had it because I installed via yaourt and I think it should pick up the latest dependencies. It's possible that it was off, though.

I just tried removing the packages and was going to install them again with yaourt, but there seems to be a circular dependency between the packages "lightdm-webkit2-greeter" and "lightdm-webkit-theme-antergos" - they both list each other in the depends section, and it goes into an infinite loop while trying to install.

I removed one of the dependencies from the configuration, and I'm installing again. I'll try rebooting and report what happens.

**Comment by YottaSecond** [comment]
Everything looked great :)

I guess there just a small issue with the AUR packages; I can post an update over there.

**Comment by lots0logs** [comment]
Okay thanks. I'm preparing the next milestone release of the greeter which will include the antergos theme as the default theme. The dependency issue with the AUR pkgbuilds will be resolved with the new release.

**Comment by YottaSecond** [comment]
Alright, thanks for your help and super-fast response! I suppose I can close this issue.

**Comment by agb80** [comment]
I'm experience same problem after today update. In my case I'm installing antergos lightdm packages directly from antergos repos added into my pacman config.

I have installed:
* lightdm-webkit2-greeter-2.0.0-1
* antergos-wallpapers 0.6-1 

What else do I need to upgrade or how can I solve this problem?

**Comment by lots0logs** [comment]
@agb80 Are you using a VM or actual hardware?

**Comment by agb80** [comment]
I'm on an actual hardware, and just realize that even similar, maybe this is a different issue, yesterday night didn't read carefully the original report.

What is happening to me is that after click on the clock it hides but nothing is displayed, all the login screen keeps blank, no login boxes. I can click on the right top arrow that appears when the clock is hide and display the clock again, just no login boxes. Wallapaper and everything all remain in screen.

I tried reinstalling the packages, even adding the archlinux antergos theme from AUR and the behavior is the same. No login boxes after click on clock.

PD: Do you think is better to create a new issue?

**Comment by lots0logs** [comment]
@agb80 Yes, I think you are having a different issue so please create a new issue for it. Also if you could include [paste2](http://paste2.org) links to the greeter logs located in `/var/log/lightdm` that would be helpful. Thanks!
