### ISSUE TITLE
LightDM Lock Screen Bug

### ISSUE THREAD

**Issue by Hippyjake** [Antergos/lightdm-webkit-theme-antergos#3]
I saw this on Google+ this morning and thought I would make an bug report.

This bug lets you get around the lock screen with just CTRL+ALT+F1.

Here is the post from G+
https://plus.google.com/112026213399155142823/posts/g7Lxo3CSgfH

**Comment by synaptiko** [comment]
I can confirm that it happens to me, I've got lightdm-webkit-theme-antergos 2.0.6-1.

**Comment by karasu** [comment]
It's not a lightdm-webkit-theme-antergos problem but a lock-extension problem.

"Antergos guys have written an extension that adds a lock icon on Shell top panel.

This extension is disabled by default, and if you enable it, what actually does (check on Gedit) is to spawn 'dm-tool lock' command.

That is supposed to lock the current seat and launches the LightDM greater.

However, it actually starts another session on another TTY, meaning that you can login to your GNOME Session without credentials, just by switching TTY (Ctrl+Alt+F1)"

**Comment by rodrigodk** [comment]
Same here, in my case i can CTRL+ALT+F7 for free access to my "locked" seat, and CTRL+ALT+F8 to go to LightDM...

**Comment by rodrigodk** [comment]
Starting `xscreensaver -no-splash &` makes dm-tool lock & dm-tool switch-to-greeter works, but CTRL+ALT+F7 returns to the unlocked seat.

**Comment by lots0logs** [comment]
For proper locking in GNOME with lightdm, special configuration is required. I don't have time to go over all of it right now but the most important points are that you need to have xscreensaver (but not configured to autostart), light-locker-settings, and our status-menu-buttons extension. You should disable all features related to locking in Gnome Settings and then use light-locker-settings to configure the lock screen. 

Cheers!

**Comment by Hippyjake** [comment]
I guess ill close this.
