### ISSUE TITLE
Add possibility to read path of background image from Javascript API

### ISSUE THREAD

**Issue by synaptiko** [Antergos/lightdm-webkit-theme-antergos#33]
Gnome Shell provides you settings of both Background and Lock screen. It would be great if theme could use Lock screen background instead of bundling wallpapers directly into themes.

Lock screen background is saved through `dconf` in `org.gnome.desktop.screensaver.picture-uri`.

It has to be some generic API not bound directly to Gnome (because you can choose different DE) but it would be nice in case of Gnome, at least.

**Comment by lots0logs** [comment]
Please check the release notes for **2.1.0 RC**

Cheers!

**Comment by synaptiko** [comment]
Oh, wonderful! :+1: And sorry I've opened it in incorrect repository.

**Comment by lots0logs** [comment]
No worries..we're in the middle of transitioning the theme to be part of the greeter so its not really obvious where to report issues right now. Sorry about that!
