### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by SamJub** [Antergos/lightdm-webkit-theme-antergos#4]
Hi there,,,

When I first installed the system I logged in without any problem, but after setting up my desktop and rebooting, lightdm wouldn't accept my password.
So, I troubleshooted the issue and managed to get to the bottom of the problem.

As an Arab, I use both Arabic and English keyboard layouts, and after doing so, the problem appears. it turned out that the greater would use the Arabic layout as a default, Even though in gnome it's set as a secondary layout.

I changed the order of layouts and **voila** I can login without a problem.

now either the login screen should get a keyboard layout switcher; or it need to read the keyboard layouts order correctly.

keep up the good work,
bye...

**Comment by lots0logs** [comment]
We've changed the theme's engine to webkit2 in the latest version (v2.0.7). Please let me know if this issue still exists. Thanks!
